# Generated by Django 2.1.4 on 2019-02-25 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pvbki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvbki_addresses', to='pvbki.Subject', verbose_name='Субъект'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvbki_collaterals', to='pvbki.Subject', verbose_name='Субъект'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvbki_communications', to='pvbki.Subject', verbose_name='Субъект'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvbki_contracts', to='pvbki.Subject', verbose_name='Субъект'),
        ),
        migrations.AlterField(
            model_name='dependant',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvbki_dependants', to='pvbki.Subject', verbose_name='Субъект'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvbki_events', to='pvbki.Subject', verbose_name='Субъект'),
        ),
        migrations.AlterField(
            model_name='identification',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvbki_identifications', to='pvbki.Subject', verbose_name='Субъект'),
        ),
        migrations.AlterField(
            model_name='monthlyincome',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvbki_incomes', to='pvbki.Subject', verbose_name='Субъект'),
        ),
        migrations.AlterField(
            model_name='record',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvbki_records', to='pvbki.Subject', verbose_name='Субъект'),
        ),
        migrations.AlterField(
            model_name='scoring',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvbki_scoring', to='pvbki.Subject', verbose_name='Субъект'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvbki_summaries', to='pvbki.Subject', verbose_name='Субъект'),
        ),
    ]
