# Generated by Django 2.1.4 on 2019-02-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvbki', '0003_edr_erbcheckup_mvscheckup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
    ]
