# Generated by Django 2.1.4 on 2019-03-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvbki', '0004_auto_20190225_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='Код')),
                ('value_ua', models.TextField(blank=True, verbose_name='Значение (UA)')),
                ('value_ru', models.TextField(blank=True, verbose_name='Значение (RU)')),
                ('value_en', models.TextField(blank=True, verbose_name='Значение (EN)')),
                ('dav', models.CharField(max_length=16, verbose_name='DAV')),
                ('model_fields', models.TextField(verbose_name='Поля моделей')),
            ],
            options={
                'verbose_name': 'Словарь',
                'verbose_name_plural': 'Словарь',
            },
        ),
    ]
