from .address import *  # noqa
from .collateral import *  # noqa
from .communication import *  # noqa
from .contract import *  # noqa
from .dependant import *  # noqa
from .event import *  # noqa
from .identification import *  # noqa
from .monthly_income import *  # noqa
from .record import *  # noqa
from .scoring import *  # noqa
from .subject import *  # noqa
from .summary import *  # noqa
from .mvs_checkup import *  # noqa
from .erb_checkup import *  # noqa
from .edr import *  # noqa
from .vocabulary import *  # noqa